### ISSUE TITLE
2 dialogs crash the app when using iron-router 

### ISSUE THREAD

**Issue by albertor24** [mizzao/meteor-jqueryui#10]
Referring to this:

http://stackoverflow.com/questions/32410382/html-comment-breaking-the-website

My app has two dialogs, and when I try to go from one page to another, my website crashes with the following error:

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

I do not know much about this bug, except that having a comment under the first dialog crashes the website.

**Comment by mizzao** [comment]
I don't think this has anything to do with this package, which just pulls in jQuery UI. You should report it with them if you think it's an issue: https://github.com/jquery/jquery-ui
