### ISSUE TITLE
What's generate.js?

### ISSUE THREAD

**Issue by trusktr** [mizzao/meteor-jqueryui#9]
Is that for Meteor? I don't see it documented anywhere.

**Comment by mizzao** [comment]
It's used to create `jqueryui.fetch.json` for a particular version of jQuery UI.

**Comment by trusktr** [comment]
@mizzao Is generate.js used by Meteor specifically? How do you know how to use it?

**Comment by mizzao** [comment]
No, it's used by my package https://github.com/mizzao/meteor-build-fetcher.

**Comment by trusktr** [comment]
@mizzao Aah, I get it! Meteor-build-fetcher is similar to what I'm working on, https://github.com/trusktr/rocket-module, but the difference is for getting stuff from npm and will let us use CommonJS or ES6 Modules in packages. Similar to how you are adding a build plugin for `fetch.json` files, I'm adding a build plugin for `main.js` files (I might rename that before releasing), where each main.js file is an entry point to be compiled by Webpack. I'm working on code-splitting right now to split dependencies across the bundles of all Meteor packages in an app.
